<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>WinExe</OutputType>
    <RootNamespace>FamilyStudio1</RootNamespace>
    <AssemblyName>FamilyStudio2</AssemblyName>
    <!--
    <IsWebBootstrapper>true</IsWebBootstrapper>
    <PublishUrl>ftp://ftp.endian.net/www/FamilyStudio/</PublishUrl>
    <Install>true</Install>
    <InstallFrom>Web</InstallFrom>
    <UpdateEnabled>true</UpdateEnabled>
    <UpdateMode>Background</UpdateMode>
    <UpdateInterval>7</UpdateInterval>
    <UpdateIntervalUnits>Days</UpdateIntervalUnits>
    <UpdatePeriodically>false</UpdatePeriodically>
    <UpdateRequired>false</UpdateRequired>
    <MapFileExtensions>true</MapFileExtensions>
    <InstallUrl>http://endian.net/FamilyStudio/</InstallUrl>
    <SupportUrl>http://endian.net/FamilyStudio</SupportUrl>
    <ProductName>FamilyStudio</ProductName>
    <PublisherName>endian.net</PublisherName>
    <SuiteName>FamilyStudio</SuiteName>
    <CreateWebPageOnPublish>true</CreateWebPageOnPublish>
    <WebPage>publish.htm</WebPage>
    <ApplicationRevision>52</ApplicationRevision>
    <ApplicationVersion>0.9.1.%2a</ApplicationVersion>
    <UseApplicationTrust>false</UseApplicationTrust>
    <PublishWizardCompleted>true</PublishWizardCompleted>
    <BootstrapperEnabled>false</BootstrapperEnabled>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    -->
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <StartupObject>FamilyStudio1.Program</StartupObject>
    <ApplicationIcon>Iconsmind-Outline-Tree.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup>
    <ManifestCertificateThumbprint>D8C0FD4E127F636D67092742D703AFD21C67267C</ManifestCertificateThumbprint>
    <ManifestKeyFile>FamilyStudio2_TemporaryKey.pfx</ManifestKeyFile>
  </PropertyGroup>
  <PropertyGroup>
    <GenerateManifests>true</GenerateManifests>
    <SignManifests>true</SignManifests>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FamilyStudioData\FamilyStudioData.csproj" />
    <ProjectReference Include="..\FamilyStudioFormsGui\FamilyStudioFormsGui.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Iconsmind-Outline-Tree.ico" />
    <Content Include="Readme.txt" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>