<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FamilyStudioConfiguration\FamilyStudioConfiguration.csproj" />
    <ProjectReference Include="..\FamilyStudioData\FamilyStudioData.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="WindowsGui\Panels\ImageViewPanel1.cs" />
  </ItemGroup>
</Project>