<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\FamilyStudioData\FamilyStudioData.csproj" />
    <ProjectReference Include="..\..\FamilyStudioWebBrowser\FamilyStudioWebBrowser.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" />
  </ItemGroup>
</Project>