<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>FamilyStudioConfiguration</AssemblyTitle>
    <Product>FamilyStudioConfiguration</Product>
    <Copyright>Copyright ©  Kenneth Ekman 2014-2016</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FamilyStudioData\FamilyStudioData.csproj" />
    <ProjectReference Include="..\FileFormats\AnarkivCodec\AnarkivCodec.csproj" />
    <ProjectReference Include="..\FileFormats\GedcomCodec\GedcomCodec.csproj" />
    <ProjectReference Include="..\FileFormats\GeniCodec\GeniCodec.csproj" />
    <ProjectReference Include="..\FileFormats\MyHeritageCodec\MyHeritageCodec.csproj" />
    <ProjectReference Include="..\FileFormats\TextCodec\TextCodec.csproj" />
  </ItemGroup>
</Project>