<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <SccProjectName>SAK</SccProjectName>
    <SccLocalPath>SAK</SccLocalPath>
    <SccAuxPath>SAK</SccAuxPath>
    <SccProvider>SAK</SccProvider>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Configurations>CD_ROM;Debug;DVD-5;Release;SingleImage</Configurations>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyTitle>GedcomCodec</AssemblyTitle>
    <Product>GedcomCodec</Product>
    <Copyright>Copyright ©  Kenneth Ekman 2014-2016</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\FamilyStudioData\FamilyStudioData.csproj" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
</Project>